package nasa

import "github.com/Marsredskies/apod_service/cmd/apod_service/database"

func init() {
	database.AddMigration(1, m1)
}

var m1 = `
CREATE TABLE public.images (
	id				BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
	,date           DATE NOT NULL
	,title			VARCHAR(255) NOT NULL
	,url			VARCHAR(255)
	,hd_url			VARCHAR(255)
	,thumb_url		VARCHAR(255)
	,media_type		VARCHAR(16) NOT NULL
    ,copyright		VARCHAR(255)
	,explanation	VARCHAR(2048) NOT NULL
	,raw_image		BYTEA NOT NULL
	,extension		VARCHAR(16)
	,created_at		TIMESTAMPTZ NOT NULL DEFAULT now()
	,deleted_at		TIMESTAMPTZ
);
`
